import { GoogleGenAI } from '@google/genai';
import { ApiResponse, UserContext } from '../types';

/**
 * GOOGLE SERVICES INTEGRATION:
 * This service is the central brain of VoteMate. It uses Google Gemini 1.5 Flash
 * for NLP intent detection, entity extraction, and complex reasoning.
 */

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY || '',
  apiVersion: 'v1',
});

const getSystemInstruction = (language: string) => `You are "VoteMate", a highly intelligent AI election assistant.
Your core mission is to guide users through the democratic process using reasoning and empathy.

AI RESPONSIBILITIES:
1. **NLP Intent Detection**: Categorize messages (eligibility_check, registration_help, deadline_lookup, etc.)
2. **Entity Extraction**: Identify 'age', 'location', and 'registrationStatus'.
3. **Dynamic Reasoning**: Explain election laws based on the user's specific context (e.g., student voting, ID requirements).
4. **Simplification**: Translate dense legal rules into simple, actionable steps.

OUTPUT: You MUST respond with a valid JSON object.
LANGUAGE: Respond entirely in ${language}.
`;

const responseSchema = {
  type: 'object',
  properties: {
    response: { type: 'string', description: "Personalized explanation generated by Gemini." },
    intent: { type: 'string' },
    userContext: {
      type: 'object',
      properties: {
        age: { type: 'number', nullable: true },
        location: { type: 'string', nullable: true },
        isRegistered: { type: 'boolean', nullable: true }
      }
    },
    currentStepId: { type: 'number' },
    suggestedReplies: { type: 'array', items: { type: 'string' } },
    timelineHighlights: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          date: { type: 'string' },
          event: { type: 'string' }
        }
      }
    }
  },
  required: ["response", "currentStepId", "suggestedReplies"],
};

export class AIService {
  /**
   * Deep Google Gemini Integration: Every message is processed here.
   * Uses Gemini 1.5 Flash for high-speed, structured reasoning.
   */
  static async processMessage(
    message: string,
    history: any[],
    context: UserContext,
    language: string
  ): Promise<ApiResponse> {
    const contents = history.map(msg => ({
      role: msg.role === 'user' ? 'user' : 'model',
      parts: [{ text: msg.content }],
    }));

    // Inject current context into the prompt for reasoning
    const contextNote = `\n[Context: Age=${context.age || 'Unknown'}, Location=${context.location || 'Unknown'}, Registered=${context.isRegistered}]\n`;
    
    // Mitigate Prompt Injection by wrapping user input
    contents.push({ 
      role: 'user', 
      parts: [{ text: `${contextNote} User Message: "${message}"` }] 
    });

    const result = await ai.models.generateContent({
      model: 'gemini-1.5-flash',
      contents,
      config: {
        systemInstruction: getSystemInstruction(language),
        temperature: 0.2,
        responseMimeType: "application/json",
        responseSchema,
      }
    });

    if (!result || !result.text) {
      throw new Error("Gemini service unavailable");
    }

    return JSON.parse(result.text) as ApiResponse;
  }
}
